meria:
  name: "Мэрия"
  leader: 10
  adminRank: 11
  gov: true
  ranks:
    - "Ранг 1"
    - "Ранг 2"
    - "Ранг 3"
    - "Ранг 4"
    - "Ранг 5"
    - "Ранг 6"
    - "Ранг 7"
    - "Ранг 8"
    - "Ранг 9"
    - "Ранг 10"
    - "Ранг 11"
  users: {}